### ISSUE TITLE
Add BBackupp to homebrew

### ISSUE THREAD

**Issue by DIYgod** [Lakr233/BBackupp#11]
Thank you for creating such a user-friendly software. However, I have been using brew to enhance my installation, uninstallation, and updating processes. Can you release software on homebrew? This document may be helpful: https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by Lakr233** [comment]
没空维护了 要不我拉你进仓库 你来提交吧

**Comment by Lakr233** [comment]
拉你了！

**Comment by Ssttar** [comment]
已在homebrew中提交
https://github.com/Homebrew/homebrew-cask/pull/181323
有些错误我稍后会修改，但大佬们可以看看帮忙修改

**Comment by Ssttar** [comment]
https://github.com/Homebrew/homebrew-cask/pull/181323/files
貌似需要签名，我对这方面有点不太熟悉

![CleanShot 2024-08-01 at 22 58 51](https://github.com/user-attachments/assets/27398002-216f-454e-956a-d74f1ca01840)

**Comment by Lakr233** [comment]
没有公证 因此签名无效 等我明天看看更新一下吧 这个版本的连接重试算法有点问题 要修一下

**Comment by Lakr233** [comment]
更新了一个带公证的软件包 但是没怎么测试过 麻烦各位发布之前测一下吧

**Comment by Zach677** [comment]
https://github.com/Homebrew/homebrew-cask/pull/181761
Waiting for merge

**Comment by Zach677** [comment]
Merged！！

**Comment by Zach677** [comment]
I would like to ask, will there be any future updates? If there are plans to update, should we consider adding it to the Homebrew autobump list?
If needed, I am happy to continue providing PR assistance.

**Comment by Lakr233** [comment]
Won’t update often, estimating 1 or 2 updates per year. The packaging script is stable and ready to use, you can set up a GitHub Action if you want the underlying binary workers to be updated automatically.
