### ISSUE TITLE
releases v2下载打开报错

### ISSUE THREAD

**Issue by xy464193** [Lakr233/BBackupp#13]
![image](https://github.com/Lakr233/BBackupp/assets/80197427/cdd77d06-e9c5-4a91-a18b-ffeff83b18bc)
releases v1.1.14 能正常打开！

**Comment by Lakr233** [comment]
看下报告呢？

**Comment by xy464193** [comment]
![image](https://github.com/Lakr233/BBackupp/assets/80197427/74f7f72e-7925-4e82-8bda-0aed263357c5)

**Comment by kotori2** [comment]
Can reproduce this issue. 估计是因为开了什么虚拟机不支持的指令集？
![image](https://github.com/user-attachments/assets/8267342a-dfc3-4a34-b424-3b2c36993e3c)

**Comment by Lakr233** [comment]
尴尬的事情是 我把符号删了 我给你们重新打一个带符号的包吧

**Comment by Lakr233** [comment]
[BBackupp.x86.7z.zip](https://github.com/user-attachments/files/16577944/BBackupp.x86.7z.zip)

这个是带符号的包 麻烦整个新的崩溃日志 谢谢

**Comment by kotori2** [comment]
因为是illegal instruction，所以感觉有崩溃栈意义不大，还是需要改编译器参数（
![image](https://github.com/user-attachments/assets/327e9e40-245a-4cb4-adcb-1433823fb564)

**Comment by Lakr233** [comment]
是 Colorful 炸了 这货用了 Metal 但是你们的设备不支持。

Swift 在 assert 的时候如果失败了会进入一个 inline 的 asm 调用 UD2 来自杀

晚点看一下上个修复吧

**Comment by Lakr233** [comment]
看下 2.14.74 吧 应该修好了 去掉了强制的要求 但可能会遇到一些奇怪的界面颜色

**Comment by kotori2** [comment]
Can confirm it works. Thanks!

**Comment by Lakr233** [comment]
昨天重写了几乎全部 ColorfulX 好蛋疼 😭
