### ISSUE TITLE
Device is connected to Mac but BBackupp v2 show a red not connected icon

### ISSUE THREAD

**Issue by qinyuhang** [Lakr233/BBackupp#14]
Hi, I have coming into a problem of not show a connected Icon in the Device View and cannot start a backup.
As the picture shows, the iPhone is connected to the Mac, and can be find in Finder.app. But BBacukupp show a red not connected icon in the Device View, right after I add the device in the app.

Do I need grant other permission to BBackupp? 

The same device and environment, I opened a BBackupp@Version 1.1 (14), it works.

macOS: 14.4.1 (23E224)
iOS: 10.3.4
BBackupp: 2.12 (66)

<img width="1507" alt="image" src="https://github.com/Lakr233/BBackupp/assets/6239057/94e16615-10a0-431b-9f70-655754875d5e">
<img width="903" alt="image" src="https://github.com/Lakr233/BBackupp/assets/6239057/e2455b62-7b78-4999-b3f6-b31e8e6494c5">

**Comment by Lakr233** [comment]
I have no idea about it. It used the almost same code for detecting devices. Try to debug yourself. :)

**Comment by qinyuhang** [comment]
Problem solved on the latest 2.13 version. With macOS 14.6.1.
Also I suspect this problem has something to do with "TripMode" App - an app from SetApp store to manage network connection, it installed Network Extension to control network access.

**Comment by Lakr233** [comment]
That’s odd. Version 2.13 doesn’t include any networking changes. 👂
