### ISSUE TITLE
how to restore from backup file

### ISSUE THREAD

**Issue by wkmyws** [Lakr233/BBackupp#23]
<img width="672" alt="image" src="https://github.com/user-attachments/assets/717233fc-f87d-4330-bc44-23406c3a311c">

I read Readme but I stil don't know how to restore from backup files

**Comment by Lakr233** [comment]
You have three options.

- Use Finder to restore it.
- Use command line from idevicebackup2
- Wait for my new app that will be released soon. (paid with free trial)

BBackupp supports backup only.
