### ISSUE TITLE
🤔 有一个疑问，可以备份iPhone相册里面的相片么？

### ISSUE THREAD

**Issue by shunichio** [Lakr233/BBackupp#3]
是否能够直接备份相册照片，还是需要其他操作，如关闭相册iCloud同步？

**Comment by Lakr233** [comment]
iCloud 没有下载的 = 没有备份

只是备份 iCloud 照片建议用 Windows 的 iCloud 自己写脚本

**Comment by shunichio** [comment]
> iCloud 没有下载的 = 没有备份
> 
> 只是备份 iCloud 照片建议用 Windows 的 iCloud 自己写脚本

没有 Windows 电脑 🤣  iCloud 没有下载的 = 没有备份，意思是如果 iCloud 照片中设置为 “下载并保留原片”，就能够备份么？

**Comment by Lakr233** [comment]
那应该没问题

**Comment by Lakr233** [comment]
iOS 备份是全盘的文件 + 应用指定不备份的排除掉（比如原神） 你就看手机上有啥吧

**Comment by shunichio** [comment]
OK，谢谢解惑。

**Comment by shunichio** [comment]
你好，我还有一个疑问，就是自动备份每次都会让输入密码信任电脑，可以省略这一步么，直接备份。 @Lakr233

**Comment by Lakr233** [comment]
嗯最近发的版本都需要了。问问你那边能同时备份两台设备吗，我这有概率会导致收不到设备数据。

**Comment by shunichio** [comment]
> 

今晚能够同时备份2台设备，6s 已经备份成功了，很小，1个G不到，另外一台还在备份。

**Comment by Lakr233** [comment]
好的 那应该是我家网络瘫了
