### ISSUE TITLE
备份目录是 Google Drive 的问题

### ISSUE THREAD

**Issue by missuo** [Lakr233/BBackupp#4]
如果备份目录选择的是 Google Drive，当一次备份完成之后，可能会删除本地，只保留云端。这样会影响下一次的 **增量备份** 嘛？

**Comment by Lakr233** [comment]
我没弄明白你的问题是什么意思。

启用增量备份有几个要求吧：
- 备份完成以后 Snapshot State 为 finished 并没有遇到严重的问题
- 目标文件系统允许移动文件夹

这么做的设计是不希望下次备份的时候 花较长的时间 准备 备份的内容，不论是 解压 还是拷贝 都没有 **保留上次备份的中间产物并直接使用** 来得快。

**删除 IncrementalCache 这个文件夹** 会直接销毁增量备份并要求下次备份执行全量备份。

**Comment by Lakr233** [comment]
哦哦那应该是不会的，只需要下载数据库那几个文件，估计大小 500M 左右。

**Comment by missuo** [comment]
> 哦哦那应该是不会的，只需要下载数据库那几个文件，估计大小 500M 左右。

好，谢谢！！
