### ISSUE TITLE
每次打开程序都会报没有权限

### ISSUE THREAD

**Issue by fgprodigal** [Lakr233/BBackupp#5]
连接的是NAS上的smb

![](https://imgur.com/CGhzEf9.png)
![](https://imgur.com/nUazpMR.png)

但是忽略后能正常备份，啥也不影响，就是开机自启的话弹这个报错有点烦😂

**Comment by Lakr233** [comment]
这个我也不知道怎么解决了 如果关掉沙盒那即使使用系统自带的保存框框也没法将备份解压到 Finder 以及 忽略以后啥都不影响是不太正常的表现

**Comment by ous50** [comment]
> 连接的是NAS上的smb
> 
> ![](https://camo.githubusercontent.com/82430d0db29134126675cdca672310f876187864ce5937fb9d2b894241688c31/68747470733a2f2f696d6775722e636f6d2f4347687a4566392e706e67) ![](https://camo.githubusercontent.com/3171f9d9f417932035e81f116319fc9593e3166d26c58e596e371ba7f1ac570e/68747470733a2f2f696d6775722e636f6d2f6e55617a704d522e706e67)
> 
> 但是忽略后能正常备份，啥也不影响，就是开机自启的话弹这个报错有点烦😂

请问你还会有备份时间超级长的问题吗？我现在一直都卡在 Transferring data……但是又不知道去哪里开debug mode

**Comment by Lakr233** [comment]
Transferring data 的意思是已经收到了设备的指令，开始传数据了。设备可能会请求 Manifest 和 文件数据库 到设备以进行 diff 增量的计算，需要等设备一段时间，长度取决于数据量。

**Comment by Lakr233** [comment]
> 但是忽略后能正常备份，啥也不影响，就是开机自启的话弹这个报错有点烦😂

可能是其他设备的设置，可以尝试重置一下 app。因为设备一旦信任就会添加到管理数据库中，目前没法删除。这个是我没设计好，下个版本重写的时候会安排。

**Comment by ous50** [comment]
> Transferring data 的意思是已经收到了设备的指令，开始传数据了。设备可能会请求 Manifest 和 文件数据库 到设备以进行 diff 增量的计算，需要等设备一段时间，长度取决于数据量。

可是很奇怪，我在Mac本地上就很快，把保存位置设置成 smb drive 上的 folder 之后，即使用有线都很慢……我应该如何取得log？

**Comment by Lakr233** [comment]
> > Transferring data 的意思是已经收到了设备的指令，开始传数据了。设备可能会请求 Manifest 和 文件数据库 到设备以进行 diff 增量的计算，需要等设备一段时间，长度取决于数据量。
> 
> 可是很奇怪，我在Mac本地上就很快，把保存位置设置成 smb drive 上的 folder 之后，即使用有线都很慢……我应该如何取得log？

你要找的不是 BBackupp 的 log 而是 smb 的 log。这个要你自己想办法了 macOS 的 smb 速度基本上不可接受。。。

**Comment by ous50** [comment]
> > > Transferring data 的意思是已经收到了设备的指令，开始传数据了。设备可能会请求 Manifest 和 文件数据库 到设备以进行 diff 增量的计算，需要等设备一段时间，长度取决于数据量。
> > 
> > 
> > 可是很奇怪，我在Mac本地上就很快，把保存位置设置成 smb drive 上的 folder 之后，即使用有线都很慢……我应该如何取得log？
> 
> 你要找的不是 BBackupp 的 log 而是 smb 的 log。这个要你自己想办法了 macOS 的 smb 速度基本上不可接受。。。

oh 原来如此

**Comment by ous50** [comment]
> > > Transferring data 的意思是已经收到了设备的指令，开始传数据了。设备可能会请求 Manifest 和 文件数据库 到设备以进行 diff 增量的计算，需要等设备一段时间，长度取决于数据量。
> > 
> > 
> > 可是很奇怪，我在Mac本地上就很快，把保存位置设置成 smb drive 上的 folder 之后，即使用有线都很慢……我应该如何取得log？
> 
> 你要找的不是 BBackupp 的 log 而是 smb 的 log。这个要你自己想办法了 macOS 的 smb 速度基本上不可接受。。。

请问大佬，我后来在 macOS 上尝试过 WebDAV 和 NFS，但 NFS 一样很慢，而 WebDAV 直接就报错权限有问题了……请问大佬是用甚么方式来把NAS挂载到 mac 上的呢？

**Comment by Lakr233** [comment]
> > > > Transferring data 的意思是已经收到了设备的指令，开始传数据了。设备可能会请求 Manifest 和 文件数据库 到设备以进行 diff 增量的计算，需要等设备一段时间，长度取决于数据量。
> > > 
> > > 
> > > 可是很奇怪，我在Mac本地上就很快，把保存位置设置成 smb drive 上的 folder 之后，即使用有线都很慢……我应该如何取得log？
> > 
> > 
> > 你要找的不是 BBackupp 的 log 而是 smb 的 log。这个要你自己想办法了 macOS 的 smb 速度基本上不可接受。。。
> 
> 请问大佬，我后来在 macOS 上尝试过 WebDAV 和 NFS，但 NFS 一样很慢，而 WebDAV 直接就报错权限有问题了……请问大佬是用甚么方式来把NAS挂载到 mac 上的呢？

我是受不了 所以换移动硬盘了

**Comment by Lakr233** [comment]
Closed due to v2.0 rewrite.
