### ISSUE TITLE
Received Failure! unableToReciveCommandFromDevice: Unable to Receive Command From Device

### ISSUE THREAD

**Issue by jizhi0v0** [Lakr233/BBackupp#6]
Received Failure! cancelled: Operation Cancelled
Received Failure! unableToReciveCommandFromDevice: Unable to Receive Command From Device

使用了加密备份(开启加密不是很顺畅 macOS 端输入两次密码后在 iOS 上输入设备密码 BBackupp还在 「please continue on device」)

macOS 14.0 Beta (23A5337a)
iOS 17.0 (21A5326a)

**Comment by Lakr233** [comment]
> 使用了加密备份(开启加密不是很顺畅 macOS 端输入两次密码后在 iOS 上输入设备密码 BBackupp还在 「please continue on device」)

设备拒绝了这个请求，刷新读到没有启用加密。这个目前貌似拿不到错误信息。。。

> Unable to Receive Command From Device

可能是网不好，我自己也遇到。。。没修好

**Comment by Lakr233** [comment]
Closed due to v2.0 rewriting.
