### ISSUE TITLE
重新连接到备份文件夹

### ISSUE THREAD

**Issue by tearfulDalvik** [Lakr233/BBackupp#7]
哈喽，下面是我发现的几个问题，小小反馈一下～
1. Backup 界面里不能选择自定义路径的备份
2. 在设置里重新连接到 Default Storage Location 会提示将覆盖文件夹里已有的备份，但强制继续并不会覆盖
3. 重新连接 Default Storage Location  后，也无法自动识别到新 Location 里已有的备份

以上问题会在更换电脑的时候无法重新连接到备份文件夹，也就无法 unpack 来还原备份了

**Comment by Lakr233** [comment]
这几个问题其实我自己都知道 主要是偷懒了 没去做

等我大概11月份我会把整个 app 重写 那时候我再来做

**Comment by tearfulDalvik** [comment]
OK，感谢开发者～～

不过请问有没有什么临时的办法让我先恢复个备份呢。。

**Comment by Lakr233** [comment]
手动 unzip 到 Finder 就行了

**Comment by tearfulDalvik** [comment]
了解，感谢！

**Comment by Lakr233** [comment]
Closed due to v2.0 rewriting.
